---
- name: Add MeiliSearch repository
  apt_repository:
    repo: "deb [trusted=yes] https://apt.fury.io/meilisearch/ /"
    state: present
    filename: fury

- name: Install MeiliSearch
  apt:
    name: meilisearch
    state: present
    update_cache: yes

- name: Enable and start MeiliSearch
  systemd:
    name: meilisearch
    state: started
    enabled: yes
